### ISSUE TITLE
Is it possible to separate out NDA files into a subdirectory?

### ISSUE THREAD

**Issue by nightblade9** [samsface/godot-steam-api#10]
Background: I'm working on a (currently) closed-source game that I'm hoping to open-source. If that happens, I need to make sure I don't have anything in Git that is covered under the Steam NDA.

From what I can see, right now, running the plugin with it being correctly configured, copies three files into the `addons/steam_api` directory. 

Is it possible to, instead, move those files into a subdirectory? That would make it rather easy for developers to open-source their games, while only needing to add a single directory to the `.gitignore` file.

**Comment by samsface** [comment]
I think it's not that much work for user to add 3 lines to their `.gitignore` if they want to do this.

```
addons/steam_api /steamsdk.dll
addons/steam_api /libsteamsdk.so
addons/steam_api /steamsdk.dylib
```

**Comment by nightblade9** [comment]
Yes, I agree. In my case, I didn't realize this until too late, and had to run `git-filter-branch` multiple times (totaling around one hour of time for it to run) to remove the relevant files from my repo history.

Also, I'm not sure if listing the files by name is okay or not; it's more obfuscated if it's just a directory, and/or if there's something in the docs about it. (Doesn't seem like you can automate it by having a local .gitignore or something, that would be ideal.)

**Comment by samsface** [comment]
This is something to think about. I'd really hate if some oblivous noob get's their steamworks account shutdown over not understanding licensees. But at the same time, most of us are developing closed source projects and want the steam sdk just bundled.

**Comment by nightblade9** [comment]
Closed without any changes?
