### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by Cobradabest** [samsface/godot-steam-api#11]
I've tried to download the add-on to Godot 3.4.3 on Ubuntu 20.04 though the AssetLib section of the client, and I followed all of the steps in the video and added a steam_appid.txt to the root of my project folder.

The example scene starts without any errors, but I don't get the Steam achievement notification, even after I've added the achievement through the steamworks dashboard.

I don't have any errors to put here, and all I get on the console is 
` 
[]`

I'm sorry I don't have any more information to provide at the moment. What do I do?

**Comment by samsface** [comment]
Did you click publish(the same button you click to publish your store page) in steamworks after adding your achievements?

Can you post the code you're using to set the achievement?

**Comment by samsface** [comment]
Closing this as there was no response.

**Comment by Cobradabest** [comment]
Sorry for the late reply, I don't go on GitHub very often.

> Did you click publish(the same button you click to publish your store page) in steamworks after adding your achievements?
I did.

> Also you don't add steam_appid.txt to the root of your project folder, it needs to be next to the Godot executable where ever you installed that.
I've tried this with a simple zip install and the itch version, and neither work.

> Can you post the code you're using to set the achievement?
I haven't modified any code yet, I just used the default code already there.
`func _ready():
	Steam.clear_achievement("NEW_ACHIEVEMENT_NAME_1_0")
	Steam.set_achievement("NEW_ACHIEVEMENT_NAME_1_0")

	Steam.set_leaderboard_score("High Score", 1000)

	var scores = yield(Steam.get_leaderboard_scores("High Score", 0, 10), "done")
	print(scores)
	
	Steam.active_game_overlay_to_web_page("https://steamcommunity.com/")
	Steam.activate_game_overlay_to_store(1435470, Steam.OverlayToStoreFlag.AddToCart)`

**Comment by Cobradabest** [comment]
Nevermind, I got it working. I think I had the app_id in the wrong place...
