### ISSUE TITLE
Problem with files in linux

### ISSUE THREAD

**Issue by PinyaColada** [samsface/godot-steam-api#15]
- OS: Manjaro Linux

Hi, once I try to import the SDK Directory it says that it cannot create the file at usr/bin, and I created it myself (just a file with the id and nothing else), however once I try print(Steam.is_init()) it stills return false, and I don't know what I'm doing wrong.

I am using the id of 480 which is just for testing.

**Comment by samsface** [comment]
https://store.steampowered.com/app/480/ isn't a valid app so that's probably your error. You need to have steam running and the app id in the file must be in the currently logged in users library.

**Comment by samsface** [comment]
https://github.com/samsface/godot-steam-api/commit/534d16e829d41c01a31a07516b50a465bac87e93#diff-0b719c2ec2cdfd7e6d6566372eefc92fe0004c00103146f81b3d6cdcd8844d26R85

Added an extra help message.
