### ISSUE TITLE
steamapp_id.txt in the readme.md but steam_appid.txt works

### ISSUE THREAD

**Issue by shoebieco** [samsface/godot-steam-api#16]
The "Testing an exported build" section of the readme.md says to create a file called steamapp_id.txt with the App ID in it, but I found (at least for my Linux builds) that I needed a file called steam_appid.txt in my exported game directory.

And THANK YOU for this plugin, you're a hero!

**Comment by samsface** [comment]
Ops, you're right. Will fix now :pray:
