### ISSUE TITLE
Rich Presence

### ISSUE THREAD

**Issue by TheMiczal** [samsface/godot-steam-api#17]
Is it possible to implement Rich Presence?

**Comment by samsface** [comment]
Yeah shouldn't be much trouble. @TheMiczal have you read the documentation for Rich Presence? Most of the work is done in SteamWorks web console because this stuff has to be localized.

**Comment by samsface** [comment]
@TheMiczal If you clone the latest, there's now support for `set_rich_presence` & `clear_rich_presence`:
https://github.com/samsface/godot-steam-api/commit/2b34f0199de1587329f1bec1f64209f8031470ed

Read the docs and test if this works. It looks like rich_presence is only visible by your friend who's already playing game :thinking:

**Comment by TheMiczal** [comment]
Hmm, in previous version steam overlay in editor was showing my games title but now it shows Godot Engine
After exporting to .exe and uploading to steam overlay shows my game title but without rich presence

This is my localisation file:
`"lang"
{
	"Language"	"english"
	"Tokens"
	{
		"#GameArea"	"In %AREA%"
		"#Status_InMainMenu"	"In Main Menu"
	}
}`
and im calling it this way:
`Steam.friends.set_rich_presence("steam_display", "#Status_InMainMenu")`
Im not exacly sure if im doing this right
@samsface

**Comment by samsface** [comment]
I think only your friends who are playing the same game will see the rich presence, that's what the docs say anyway.

**Comment by TheMiczal** [comment]
Steam hasnt approved my steam page yet so my friend dont even see my game in library so ill have to wait lol
But thank you so much for adding this~

**Comment by TheMiczal** [comment]
Idk why but works perfectly fine now, thanks again a lot <3
