### ISSUE TITLE
Can't get Steam Username

### ISSUE THREAD

**Issue by DaelonSuzuka** [samsface/godot-steam-api#19]
There doesn't seem to be a way to get the user's Steam name.

Steamworks API docs say that I need to call [`ISteamFriends.GetPersonaName`](https://partner.steamgames.com/doc/api/ISteamFriends#GetPersonaName), but for some reason that's not exposed in the API here.

This seems like a very basic thing I might want to do, so is a different method to achieve this already implemented?

**Comment by samsface** [comment]
The whole API isn’t exposed, I add stuff as people request it. 
It looks like a simple function to add though, open a PR and I’ll merge. Else I’ll add it this week when I can 🙏.

**Comment by samsface** [comment]
@DaelonSuzuka I've added now, can you test it works so can close the issue?

**Comment by DaelonSuzuka** [comment]
Wow, that was fast, thanks a lot!

It works fine on Windows as far as I can tell.

![image](https://user-images.githubusercontent.com/18042232/168455588-1e561aa5-1675-455f-b6ce-27e77f47b881.png)

**Comment by samsface** [comment]
Awesome, will close :sunglasses:
