### ISSUE TITLE
Exported Release cannot connect to Steam

### ISSUE THREAD

**Issue by DaisyGames** [samsface/godot-steam-api#2]
I exported my game as a release and when I launch it, it doesn't connect to Steam, so the Steam API integration stops working.
When I ran the game from Godot editor, it worked fine.

Another to thing to note is that when I upload it the build to Steam and launch it from there, it works fine.

**Comment by samsface** [comment]
Right, you need a file named "steam_appid.txt" with just the steam app id inside. Will add this to readme,
