### ISSUE TITLE
[BUG] Cannot get it to work between Godot and Steam

### ISSUE THREAD

**Issue by zapposh** [samsface/godot-steam-api#20]
- OS: Windows 10 / Godot 3.4.4

I don't think it is necessarily a bug, but I cannot get it to work.

**Describe the issue**
The game/ID is in my library (but there is no game executable on Steamworks yet), steam_appid.txt has the correct number, and is located next to godot.exe. Steam.is_init() returns true after launch. Steam.set_achievement("xyz") does nothing, and Steam.get_achievement("xyz") returns false.
Same for the leaderboards, which are also defined in Steamworks. I must have missed something, but cannot locate the error.

**Paste the code causing the issue**
```gdscript
func _ready():
	if(steamVersion):
		if Steam.is_init():
			Steam.set_achievement("burger_time")
			var has_alredy_unlocked_achievement:bool = Steam.get_achievement("burger_time")
			print(has_alredy_unlocked_achievement) #prints false
			set_steam_leaderboards()

func set_steam_leaderboards():
	if GameManager.current_game_mode == GameManager.current_player_game_data["easy_mode"]:
		Steam.set_leaderboard_score("EasyMedium", GameManager.Score)
	elif GameManager.current_game_mode == GameManager.current_player_game_data["medium_mode"]:
		Steam.set_leaderboard_score("MediumHard", GameManager.Score)
	elif GameManager.current_game_mode == GameManager.current_player_game_data["speedrun_mode"]:
		Steam.set_leaderboard_score("SugarRushSpeedrun", GameManager.TotalGameTime)
	elif GameManager.current_game_mode == GameManager.current_player_game_data["daily_challenge"]:
		Steam.set_leaderboard_score("DailyHighScore", GameManager.Score)
	print("Leaderboards updated") #number of entries on Steamworks are still at 0
```

**Paste any error appearing in the console**
```godot console
None
```
![godot_steam](https://user-images.githubusercontent.com/9380614/169074308-8b471a4e-bb35-4b2d-8d70-5d44b70489c1.png)

The ID (1779560) is also correct (https://store.steampowered.com/app/1779560/Donut_Dodo/)
Thanks.

**Comment by samsface** [comment]
I don't think you need any executable up on Steam :thinking:, everything should work right out of the Godot editor.

Is it possible you didn't click publish after adding your achievements? What happens if you run this code:

```gdscript
for i in Steam.user_stats.get_num_achievements():
	   print(Steam.user_stats.get_achievement_name(i))
```

**Comment by samsface** [comment]
@zapposh I'm thinking maybe the no build uploaded to depot could be the issue.

Can you dm me on discord, I want to test something https://discord.gg/rPvvUAZJ

**Comment by samsface** [comment]
OK so the issue here was we were launch Godot from Steam. So Steam injected Godot's appid into the application meaning we were trying to set the achievements for Godot : )

There's no work around for this. You just have to launch outside of steam. I'll add an error message to this effect.
