### ISSUE TITLE
[BUG] Couldn't fully load the singleton script "Steam" (possible cyclic reference or parse error)

### ISSUE THREAD

**Issue by DotSquareGames** [samsface/godot-steam-api#21]
- OS: MacOS

**Describe the issue**
Basically, if I try to use a function with the Steam library (like, say, Steam.clear_achievement("test") for example), I have an error message saying that "Couldn't fully load the singleton script "Steam" (possible cyclic reference or parse error)". At first I did not have any message errors in the console, but now I have a few (listed below).
I tried it on a copy of my current project, and for one of them it seems to work fine, but not for the other one.
Weirdly enough, even in the one with all the error messages, it now seems to work (in the sense that the achievement is unlocked), even though I have a bunch of scary error messages.

**Paste the code causing the issue**
```gdscript
func _ready():
# Test steam achievements
	Steam.clear_achievement("test")
	Steam.set_achievement("test")
	print(Steam.user_stats.get_achievement_name(0))
```

**Paste any error appearing in the console**
```godot console
 Resource: 'res://addons/steam_api/steam.gd' is already being loaded. Cyclic reference?
 res://addons/steam_api/steam.gd:5 - Parse Error: The identifier "Steam" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR
 Resource: 'res://addons/steam_api/steam.gd' is already being loaded. Cyclic reference?
 res://addons/steam_api/steam.gd:5 - Parse Error: The identifier "Steam" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR

```

**Comment by samsface** [comment]
@DotSquareGames Can you zip up a simple Godot project that reproduces the error?

**Comment by DotSquareGames** [comment]
Hi!There's something weird about the bug I mentioned. Basically, now it's different again: the achievements don't work anymore in the project where it used to work but had error messages. However, if I put the build into steam and launch the game from there, it works perfectly, apparently. No idea why. The game is exactly the same...So, to put it simply: it seems that I have errors or actual bug that prevent the achievement system to work properly on Godot itself, but when the build is launched from Steam, it seems (so far) to work.

I created a simple Godot project like you asked, but on this one, for some reason, it does not have any bug. I'm not sure why. But I tried again in another game of mine, and the same error happened. It seems that the error happen only on project that are not new and empty...
Not sure what I can do to help you...

**Comment by samsface** [comment]
I really can't help unless I have a project that can reproduce your issue :shrug:

**Comment by samsface** [comment]
@DotSquareGames I think I see the issue. Can you try this for me?

https://github.com/samsface/godot-steam-api/blob/49dd642fa183138fb9f4ed96bbffc294d3ef9c94/addons/steam_api/steam.gd#L5

In the file at the linke linked above

```diff
-if Steam.utils.get_app_id() == godot_steam_app_id:
+if utils.get_app_id() == godot_steam_app_id:
```
