### ISSUE TITLE
Order of autoloads changed by the EditorPlugin

### ISSUE THREAD

**Issue by MrEliptik** [samsface/godot-steam-api#24]
Because the `steam.gd` singleton  is added by the `EditorPlugin` dynamically, it's always put at the end of the autoload list. It seems we can't decide the order when adding a singleton by code unfortunately, unless I missed something?

This is not a huge problem, it's possible to go around this limitation but I just wanted to talk about it in case someone else is having the same problem. It's frustrating to set the order in the settings and then getting it overridden. 

If there's no other solution, maybe we could add a warning somewhere in the readme or in the SteamAPI project settings panel?

**Comment by samsface** [comment]
@MrEliptik What exactly is the problem with the autoload appearing at the bottom of the list?

**Comment by MrEliptik** [comment]
In my case I wanted the Steam singleton to be loaded first because I had other singletons using it to do different things. As I said in my first message, it's not a deal breaker, I can do something else. It's just that I didn't understand why it would always go back to being at the bottom of the list even though I moved it.

**Comment by samsface** [comment]
@MrEliptik So you have your own autoload, that during it's `_ready` function, call the Steam Autload before it's called it's `_ready` function?

**Comment by MrEliptik** [comment]
@samsface Yes exactly and I wasn't aware the Steam plugin was going to change the order of the autoload by adding the Steam.gd dynamically.

**Comment by samsface** [comment]
@MrEliptik Ok gotcha. Is there a way to check if a script is already autoloaded? Then we could not add the autoload automatically if it's already there.

**Comment by MrEliptik** [comment]
By looking at some GitHub issues, some people recommend opening the **project.godot** as a `ConfigFile` and looking at the autoload section, but I found a very simple way using `ProjectSettings`. 

You can check if the autoload is present by doing: `ProjectSettings.get("autoload/Steam")`
this returns the script path if present, otherwise `null`

**Comment by samsface** [comment]
Neat, added a check using this and seems to work :pray:
