### ISSUE TITLE
It doesn't work with 32-bit games.

### ISSUE THREAD

**Issue by dannygaray60** [samsface/godot-steam-api#25]
Hello! The plugins seems works fine, but I noticed that exported 32 bits exe's doesn't works and I got this error messages:

![Captura de pantalla (2)](https://user-images.githubusercontent.com/30391210/185255411-ab286495-f3a1-479b-aacc-acadd4de5251.png)

This is plugin only for x64 games? If this is the case, it should be clarified in the readme.

PS: Thanks for this great plugin!

**Comment by samsface** [comment]
@dannygaray60  There's no 32 bit build but it should be possible if you know C++ and want to try yourself.
Are you really confined to 32 bit builds?

**Comment by dannygaray60** [comment]
Thanks for replying! 

It's not a major problem, but considering that godot still offers 32bit support I thought it could at least be mentioned in the readme. And I'm already published 32bits builds on steam

**Comment by samsface** [comment]
I can provide a 32bit build if someone is really stuck. But until then, just don't want to maintain that. But added a mention to the readme.
