### ISSUE TITLE
Querying game language using GetCurrentGameLanguage()

### ISSUE THREAD

**Issue by MrEliptik** [samsface/godot-steam-api#26]
Exposing `GetCurrentGameLanguage` might be useful to get the language the user has selected in Steam. 

As Steam suggests [here](https://partner.steamgames.com/doc/store/localization#ingame), if you have only one depot for your game with all the languages, you can query the language selected by the user using `ISteamApps::GetCurrentGameLanguage`. At the same time, `GetAvailableGameLanguages` might be useful too.

**Comment by samsface** [comment]
Added both functions. Fyi, the GetAvailableGameLanguages returns a comma separated list of langs and not an array. Just how Steam does it :shrug:.
