### ISSUE TITLE
Ability to disable plugin at runtime

### ISSUE THREAD

**Issue by nightblade9** [samsface/godot-steam-api#28]
Is it possible to add a function I can call, to disable the Steam integration at runtime?

I use the same code-base for the demo and full version of my game. In my export settings, I have two exports for each platform: one for the demo, and one for the full game. If possible, I would like to disable Steam integration in the demo version, by calling some function to disable the API if I detect the game is running in demo mode.

**Comment by samsface** [comment]
The switch in project settings won't work for you? @nightblade9

**Comment by nightblade9** [comment]
If you mean the project setting under the SteamAPI tab, no, that won't work; I need a way to flip the value in code.

For now, I figured out a work-around on my side (if my game is in demo mode, don't call any of the Steam APIs). It would be nice to be able to turn off the Steam API integration completely.

**Comment by nightblade9** [comment]
Awesome, thanks for making this change.
