### ISSUE TITLE
could we have a 3.4-compatible version, please?

### ISSUE THREAD

**Issue by weareRODEONET** [samsface/godot-steam-api#29]
Hi, thank you for taking the time to read this. I am a solo independent game developer, and my game is incompatible with the 3.5 version of Godot. I was wondering if there was a simple way to release a 3.4-compatible branch, or some guidance on making this steam API integration compatible with 3.4?

This seems like a worthwhile asset especially for 3.5 adopters, I would like to also use this API for the game's Steam Release.

I appreciate your investigation.

**Comment by samsface** [comment]
It works with 3.4 just fine. What has preventing you from using the plugin with Godot 3.4?

**Comment by weareRODEONET** [comment]
My own ineptitude. I was doing something silly. I gave it another go and got it working without randomly crashing the application.
I appreciate your response, this does properly work with Godot 3.4.
