### ISSUE TITLE
Changing Steam App ID doesn't work

### ISSUE THREAD

**Issue by DaisyGames** [samsface/godot-steam-api#3]
Hi, I needed to change the Steam App ID for my project and it doesn't work.

I go into Project Settings -> SteamAPI.
Then I rewrite the ID in Steam App ID and it keeps connecting to the old ID.

Thanks!

**Comment by samsface** [comment]
Ok see why this is confusing. You need to click `Import SDK` again. I'll change the button text to be more clear.

**Comment by DaisyGames** [comment]
> Ok see why this is confusing. You need to click `Import SDK` again. I'll change the button text to be more clear.
That worked, thanks!
