### ISSUE TITLE
UserStats does not have a ResetAllStats call implemented

### ISSUE THREAD

**Issue by Aarimous** [samsface/godot-steam-api#33]
Hi, I'm using this addon for my game Chess Survivors and I wanted to call ResetAllStats prior to the launch of my game. I'm using Steam stats to track my games general balance and as such would like to be able to reset it as I patch the game. One of the nice things about the method is you can pass in a bool if you also want to clear achievements.  

https://partner.steamgames.com/doc/api/ISteamUserStats#ResetAllStats

**Comment by samsface** [comment]
@Aarimous added it. Can test the latest build here: https://github.com/samsface/godot-steam-api/archive/refs/heads/master.zip.

**Comment by Aarimous** [comment]
Sorry, I've been working on bugs as I launched my game yesterday. I'll test this out over the weekend. Cheers!
