### ISSUE TITLE
Steam.utils.is_running_on_steam_deck() returns an error and crashes engine

### ISSUE THREAD

**Issue by starsidecosmos** [samsface/godot-steam-api#36]
Steam.utils.is_running_on_steam_deck() returns nonexistent function 'is_running_on_steam_deck' in base Reference() error and crashes the engine.

Perhaps the official Godot repositories are not updated yet? However, I did download a zipped version of the master and the same thing occurred.

For reference, I'm on Ubuntu 22.04.1 LTS. Steam is currently running in the background, but Godot is being launched via Itch.

**Comment by samsface** [comment]
@starsidecosmos Can you screenshot the full error output from Godot please?

What version of the steam api are you using? `is_running_on_steam_deck` was added recently.

**Comment by starsidecosmos** [comment]
Just downloaded and reimported version 1.55 of the steamworks sdk.

![Screenshot from 2023-01-05 12-46-14](https://user-images.githubusercontent.com/76600284/210847202-6c940a0f-098b-4bc0-b52d-f91e938bb5a1.png)

**Comment by samsface** [comment]
@starsidecosmos If you check your steam_i.gd file, does it have this function? https://github.com/samsface/godot-steam-api/blob/743b413022e55309c6498b5143a25f8193217baf/addons/steam_api/steam_i.gd#L200

**Comment by starsidecosmos** [comment]
It does not.

I tried redownloading from the official repositories and it still doesn't appear. Perhaps the official repositories aren't updated yet?

**Comment by samsface** [comment]
@starsidecosmos I've just requested the latest commit be used on the Asset Library. It's a manual process so my take a few days. You could also try download the plugin directly from this repo: https://github.com/samsface/godot-steam-api/archive/refs/heads/master.zip

**Comment by starsidecosmos** [comment]
Thanks! I did that before opening the issue, but I must not have implemented it correctly. 

I've currently found a solution by using Steam's built-in Steamdeck-only depots and a custom Steamdeck Godot export with a "steamdeck" feature tag.
