### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by starYTlol** [samsface/godot-steam-api#41]
Can I add this plugin, make my game (without Steam features) and then add project ID and extract SDK? Otherwords, can I make my game and after that add SteamSDK and plugin?

**Comment by samsface** [comment]
Yeah when you add the plugin, there's a tab in project settings added.
In this tab there's a checkbox to disable the plugin (there's also an export option to trigger it) that disables the plugin.
I put it in for people that also publish on itch and stuff.

**Comment by starYTlol** [comment]
But can I first make a game and than extract SDK?
Like make a map, 3D models and stuff and then go to plugin and extract SDK into my files?

**Comment by samsface** [comment]
Yeah you can make the game first and add this later if that's what you mean.

**Comment by starYTlol** [comment]
Yes! Thanks man, you're best!
