### ISSUE TITLE
Please clarify license of src/Godot.cpp

### ISSUE THREAD

**Issue by rfht** [samsface/godot-steam-api#42]
Hi,

The license of this file is unclear. I can only find MIT license in addons/steam_api. Is this code on Godot.cpp also meant to be MIT licensed? Would probably be best to just have it at the beginning of the file as comment to have clarity.

**Comment by samsface** [comment]
The entire project is under MIT license. The license file is located in `addons/steam_api` so it'll be bundled with the plugin when consumed through the steam asset library.
