### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by Awfyboy** [samsface/godot-steam-api#44]
I'm already stuck on Step 1. I'm using Godot 3.5.3 and I'm trying to install the plugin. I tried downloading it from the Asset Library and importing the file from Github, but I get the following error:
` Can't open dynamic library: D:/Awf/Projects/_TEST PROJECTS_/SteamIntegrationTest/addons/steam_api/steamsdk-godot.dll, error: Error 126: The specified module could not be found.
.
 modules/gdnative/gdnative.cpp:510 - No valid library handle, can't get symbol from GDNative object
 modules/gdnative/nativescript/nativescript.cpp:1503 - No nativescript_init in "res://addons/steam_api/steamsdk-godot.dll" found
 Can't open dynamic library: D:/Awf/Projects/_TEST PROJECTS_/SteamIntegrationTest/addons/steam_api/steamsdk-godot.dll, error: Error 126: The specified module could not be found.
.
 modules/gdnative/gdnative.cpp:510 - No valid library handle, can't get symbol from GDNative object
 modules/gdnative/nativescript/nativescript.cpp:1503 - No nativescript_init in "res://addons/steam_api/steamsdk-godot.dll" found
 Can't open dynamic library: D:/Awf/Projects/_TEST PROJECTS_/SteamIntegrationTest/addons/steam_api/steamsdk-godot.dll, error: Error 126: The specified module could not be found.
.
 modules/gdnative/gdnative.cpp:510 - No valid library handle, can't get symbol from GDNative object
 modules/gdnative/nativescript/nativescript.cpp:1503 - No nativescript_init in "res://addons/steam_api/steamsdk-godot.dll" found
`

**Comment by samsface** [comment]
@Awfyboy did you download the steam sdk and add it into the same directory of the addon? You can download it through steam works

**Comment by Awfyboy** [comment]
@samsface I ended up using another plugin. I suppose adding the Steam SDK might help but I haven't checked it. I really wish this was mentioned in the Getting Started section.
