### ISSUE TITLE
Godot exports Steam dlls even when Plugin is disabled.

### ISSUE THREAD

**Issue by DaisyGames** [samsface/godot-steam-api#5]
Hey, I disabled your plugin, even removed Steam.tscn from autoload but when I export my project, it creates the steam_api64.dll and steamsdk-godot.dll anyway.

**Comment by samsface** [comment]
Maybe custom file filters on project export could help? I never thought about not wanting to export tbh, I’ll look into it.

**Comment by snoopdouglas** [comment]
I've resorted to making a 'null plugin' that stubs out the `Steam`, `SteamAPI` etc. classes. For Steam builds, I duplicate the entire project and replace the null plugin with the real one. This ensures Godot doesn't complain about missing classes or files.

[steam_api_null.zip](https://github.com/samsface/godot-steam-api/files/7574491/steam_api_null.zip)

**Comment by samsface** [comment]
I've added a switch in `steam api > project` settings to make all Steam calls do nothing for people dual publishing to itch or whatever.
